name: API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # setup postgresql test database
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd backend
          npm install
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/testdb
          
      - name: Setup Prisma and database
        run: |
          cd backend
          npx prisma generate --schema=server/prisma/schema.prisma
          npx prisma db push --schema=server/prisma/schema.prisma
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/testdb
          
      - name: Run API tests
        run: |
          cd backend
          npx vitest
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/testdb 
          NODE_ENV: test 